# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.http_http_response import HttpHttpResponse

class TestHttpHttpResponse(unittest.TestCase):
    """HttpHttpResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpHttpResponse:
        """Test HttpHttpResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpHttpResponse`
        """
        model = HttpHttpResponse()
        if include_optional:
            return HttpHttpResponse(
                code = 56,
                data = None,
                error = '',
                message = '',
                success = True
            )
        else:
            return HttpHttpResponse(
        )
        """

    def testHttpHttpResponse(self):
        """Test HttpHttpResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
