# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_role import ModelRole

class TestModelRole(unittest.TestCase):
    """ModelRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelRole:
        """Test ModelRole
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelRole`
        """
        model = ModelRole()
        if include_optional:
            return ModelRole(
                created_at = '',
                created_by = 56,
                desc = '',
                id = 56,
                original = True,
                role_type = 0,
                status = '',
                updated_at = '',
                updated_by = 56
            )
        else:
            return ModelRole(
        )
        """

    def testModelRole(self):
        """Test ModelRole"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
