# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.messaging_crt_order import MessagingCrtOrder

class TestMessagingCrtOrder(unittest.TestCase):
    """MessagingCrtOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessagingCrtOrder:
        """Test MessagingCrtOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessagingCrtOrder`
        """
        model = MessagingCrtOrder()
        if include_optional:
            return MessagingCrtOrder(
                account_id = 56,
                comment = '',
                expiration_police = 0,
                order_price = 1.337,
                price_sl = 1.337,
                price_tp = 1.337,
                side = 0,
                symbol_id = 56,
                time_expiration = '',
                type = 0,
                user_id = 56,
                volume = 1.337
            )
        else:
            return MessagingCrtOrder(
                account_id = 56,
                order_price = 1.337,
                symbol_id = 56,
                user_id = 56,
                volume = 1.337,
        )
        """

    def testMessagingCrtOrder(self):
        """Test MessagingCrtOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
