# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.messaging_close_position import MessagingClosePosition

class TestMessagingClosePosition(unittest.TestCase):
    """MessagingClosePosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessagingClosePosition:
        """Test MessagingClosePosition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessagingClosePosition`
        """
        model = MessagingClosePosition()
        if include_optional:
            return MessagingClosePosition(
                account_id = 56,
                id = 56,
                user_id = 56,
                volume = 1.337
            )
        else:
            return MessagingClosePosition(
                account_id = 56,
                id = 56,
                user_id = 56,
                volume = 1.337,
        )
        """

    def testMessagingClosePosition(self):
        """Test MessagingClosePosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
