# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.symbols_api import SymbolsApi


class TestSymbolsApi(unittest.TestCase):
    """SymbolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SymbolsApi()

    def tearDown(self) -> None:
        pass

    def test_get_trader_symbol(self) -> None:
        """Test case for get_trader_symbol

        """
        pass

    def test_get_trader_symbol_ticks_history(self) -> None:
        """Test case for get_trader_symbol_ticks_history

        """
        pass

    def test_get_trader_symbols(self) -> None:
        """Test case for get_trader_symbols

        """
        pass


if __name__ == '__main__':
    unittest.main()
