# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_approval_trader_order(self) -> None:
        """Test case for approval_trader_order

        """
        pass

    def test_cancel_trader_order(self) -> None:
        """Test case for cancel_trader_order

        """
        pass

    def test_create_trader_order(self) -> None:
        """Test case for create_trader_order

        """
        pass

    def test_get_trader_order(self) -> None:
        """Test case for get_trader_order

        """
        pass

    def test_get_trader_orders(self) -> None:
        """Test case for get_trader_orders

        """
        pass

    def test_get_trader_orders_history(self) -> None:
        """Test case for get_trader_orders_history

        """
        pass

    def test_update_trader_order(self) -> None:
        """Test case for update_trader_order

        """
        pass


if __name__ == '__main__':
    unittest.main()
