# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_source_of_wealth import ModelSourceOfWealth

class TestModelSourceOfWealth(unittest.TestCase):
    """ModelSourceOfWealth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelSourceOfWealth(self):
        """Test ModelSourceOfWealth"""
        # inst = ModelSourceOfWealth()

if __name__ == '__main__':
    unittest.main()
