# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.messaging_history_tick import MessagingHistoryTick

class TestMessagingHistoryTick(unittest.TestCase):
    """MessagingHistoryTick unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessagingHistoryTick:
        """Test MessagingHistoryTick
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessagingHistoryTick`
        """
        model = MessagingHistoryTick()
        if include_optional:
            return MessagingHistoryTick(
                close = 1.337,
                high = 1.337,
                low = 1.337,
                open = 1.337,
                time = 56,
                volume = 1.337
            )
        else:
            return MessagingHistoryTick(
        )
        """

    def testMessagingHistoryTick(self):
        """Test MessagingHistoryTick"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
