# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_document_type import ModelDocumentType

class TestModelDocumentType(unittest.TestCase):
    """ModelDocumentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelDocumentType(self):
        """Test ModelDocumentType"""
        # inst = ModelDocumentType()

if __name__ == '__main__':
    unittest.main()
