# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.messaging_open_account import MessagingOpenAccount

class TestMessagingOpenAccount(unittest.TestCase):
    """MessagingOpenAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessagingOpenAccount:
        """Test MessagingOpenAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessagingOpenAccount`
        """
        model = MessagingOpenAccount()
        if include_optional:
            return MessagingOpenAccount(
                address = '',
                balance = 56,
                email = '',
                family_name = '',
                first_name = '',
                investor_password = '',
                middle_name = '',
                user_password = '',
                username = ''
            )
        else:
            return MessagingOpenAccount(
                balance = 56,
                first_name = '',
                investor_password = '',
                user_password = '',
                username = '',
        )
        """

    def testMessagingOpenAccount(self):
        """Test MessagingOpenAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
