# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.positions_api import PositionsApi


class TestPositionsApi(unittest.TestCase):
    """PositionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PositionsApi()

    def tearDown(self) -> None:
        pass

    def test_close_trader_position(self) -> None:
        """Test case for close_trader_position

        """
        pass

    def test_get_trader_position(self) -> None:
        """Test case for get_trader_position

        """
        pass

    def test_get_trader_positions(self) -> None:
        """Test case for get_trader_positions

        """
        pass

    def test_get_trader_positions_history(self) -> None:
        """Test case for get_trader_positions_history

        """
        pass

    def test_update_trader_position(self) -> None:
        """Test case for update_trader_position

        """
        pass


if __name__ == '__main__':
    unittest.main()
