# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_margin_mode import ModelMarginMode

class TestModelMarginMode(unittest.TestCase):
    """ModelMarginMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelMarginMode(self):
        """Test ModelMarginMode"""
        # inst = ModelMarginMode()

if __name__ == '__main__':
    unittest.main()
