# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.messaging_trader_order_approval import MessagingTraderOrderApproval

class TestMessagingTraderOrderApproval(unittest.TestCase):
    """MessagingTraderOrderApproval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessagingTraderOrderApproval:
        """Test MessagingTraderOrderApproval
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessagingTraderOrderApproval`
        """
        model = MessagingTraderOrderApproval()
        if include_optional:
            return MessagingTraderOrderApproval(
                account_id = 56,
                approved = True,
                id = 56,
                user_id = 56
            )
        else:
            return MessagingTraderOrderApproval(
                account_id = 56,
                id = 56,
                user_id = 56,
        )
        """

    def testMessagingTraderOrderApproval(self):
        """Test MessagingTraderOrderApproval"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
