# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.deals_api import DealsApi


class TestDealsApi(unittest.TestCase):
    """DealsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DealsApi()

    def tearDown(self) -> None:
        pass

    def test_get_trader_deal(self) -> None:
        """Test case for get_trader_deal

        """
        pass

    def test_get_trader_deals(self) -> None:
        """Test case for get_trader_deals

        """
        pass


if __name__ == '__main__':
    unittest.main()
