# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_education_level import ModelEducationLevel

class TestModelEducationLevel(unittest.TestCase):
    """ModelEducationLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelEducationLevel(self):
        """Test ModelEducationLevel"""
        # inst = ModelEducationLevel()

if __name__ == '__main__':
    unittest.main()
