# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.model_exit_level import ModelExitLevel

class TestModelExitLevel(unittest.TestCase):
    """ModelExitLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelExitLevel(self):
        """Test ModelExitLevel"""
        # inst = ModelExitLevel()

if __name__ == '__main__':
    unittest.main()
