# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelEducationLevel(int, Enum):
    """
    ModelEducationLevel
    """

    """
    allowed enum values
    """
    EducationLevel_none = 0
    EducationLevel_high_school = 1
    EducationLevel_bachelor_degree_or_equivalent = 2
    EducationLevel_master_degree_or_equivalent = 3
    EducationLevel_phd_or_equivalent = 4
    EducationLevel_other = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelEducationLevel from a JSON string"""
        return cls(json.loads(json_str))


