# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelTradingExperience(int, Enum):
    """
    ModelTradingExperience
    """

    """
    allowed enum values
    """
    TradingExperience_less_than_1_year = 0
    TradingExperience_1_3_years = 1
    TradingExperience_more_than_5_years = 2

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelTradingExperience from a JSON string"""
        return cls(json.loads(json_str))


