# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelEmploymentIndustry(int, Enum):
    """
    ModelEmploymentIndustry
    """

    """
    allowed enum values
    """
    EmploymentIndustry_none = 0
    EmploymentIndustry_agriculture_food_and_natural_resource = 1
    EmploymentIndustry_architecture_and_construction = 2
    EmploymentIndustry_business_management_and_administration = 3
    EmploymentIndustry_arts_audio_video_technology_and_communication = 4
    EmploymentIndustry_education_and_training = 5
    EmploymentIndustry_government_and_public_administration = 6
    EmploymentIndustry_healthcare = 7
    EmploymentIndustry_hospitality_and_tourism = 8
    EmploymentIndustry_information_technology = 9
    EmploymentIndustry_legal_public_safety_corrections_and_security = 10
    EmploymentIndustry_manufacturing = 11
    EmploymentIndustry_marketing_and_sales = 12
    EmploymentIndustry_science_and_technology = 13
    EmploymentIndustry_engineering_and_mathematics = 14
    EmploymentIndustry_transportation_distribution_and_logistics = 15
    EmploymentIndustry_other = 16

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelEmploymentIndustry from a JSON string"""
        return cls(json.loads(json_str))


