# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelChannelType(int, Enum):
    """
    ModelChannelType
    """

    """
    allowed enum values
    """
    ChannelType_mobile = 0
    ChannelType_web = 1
    ChannelType_desktop = 2
    ChannelType_api = 3
    ChannelType_script = 4
    ChannelType_system = 5
    ChannelType_sdk = 6

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelChannelType from a JSON string"""
        return cls(json.loads(json_str))


