# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from omtrader.rest.models.model_exit_level import ModelExitLevel
from omtrader.rest.models.model_expiration_policy import ModelExpirationPolicy
from omtrader.rest.models.model_fill_policy import ModelFillPolicy
from omtrader.rest.models.model_order_status import ModelOrderStatus
from omtrader.rest.models.model_order_type import ModelOrderType
from omtrader.rest.models.model_reason_type import ModelReasonType
from omtrader.rest.models.model_side_type import ModelSideType
from omtrader.rest.models.model_symbol import ModelSymbol
from typing import Optional, Set
from typing_extensions import Self

class ModelOrder(BaseModel):
    """
    ModelOrder
    """ # noqa: E501
    account: Optional[ModelTradeAccount] = None
    account_id: Optional[StrictInt] = None
    comment: Optional[StrictStr] = None
    contract_size: Optional[Union[StrictFloat, StrictInt]] = None
    created_at: Optional[StrictStr] = None
    created_by: Optional[StrictInt] = None
    dealer_id: Optional[StrictInt] = None
    digits: Optional[StrictInt] = Field(default=None, description="configured digits to use for this positions")
    digits_currency: Optional[StrictInt] = Field(default=None, description="currency digits")
    exit_level: Optional[ModelExitLevel] = Field(default=None, description="when to exit overide S/L")
    exit_loos: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="exit loos value for the position")
    exit_profit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="exit profit value for the position")
    expiration_policy: Optional[ModelExpirationPolicy] = None
    external_id: Optional[StrictStr] = Field(default=None, description="id of position on LP")
    id: Optional[StrictInt] = None
    position: Optional[ModelPosition] = None
    position_by: Optional[ModelPosition] = None
    position_by_id: Optional[StrictInt] = None
    position_id: Optional[StrictInt] = None
    price_current: Optional[Union[StrictFloat, StrictInt]] = None
    price_order: Optional[Union[StrictFloat, StrictInt]] = None
    price_sl: Optional[Union[StrictFloat, StrictInt]] = None
    price_tp: Optional[Union[StrictFloat, StrictInt]] = None
    price_trigger: Optional[Union[StrictFloat, StrictInt]] = None
    rate_margin: Optional[Union[StrictFloat, StrictInt]] = None
    reason: Optional[ModelReasonType] = None
    side: Optional[ModelSideType] = None
    status: Optional[ModelOrderStatus] = None
    symbol: Optional[ModelSymbol] = None
    symbol_id: Optional[StrictInt] = Field(default=None, description="symbol id")
    time_done: Optional[StrictStr] = None
    time_expiration: Optional[StrictStr] = None
    time_setup: Optional[StrictStr] = None
    type: Optional[ModelOrderType] = None
    type_fill: Optional[ModelFillPolicy] = None
    type_time: Optional[StrictInt] = None
    updated_at: Optional[StrictStr] = None
    updated_by: Optional[StrictInt] = None
    volume_current: Optional[Union[StrictFloat, StrictInt]] = None
    volume_current_ext: Optional[Union[StrictFloat, StrictInt]] = None
    volume_initial: Optional[Union[StrictFloat, StrictInt]] = None
    volume_initial_ext: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["account", "account_id", "comment", "contract_size", "created_at", "created_by", "dealer_id", "digits", "digits_currency", "exit_level", "exit_loos", "exit_profit", "expiration_policy", "external_id", "id", "position", "position_by", "position_by_id", "position_id", "price_current", "price_order", "price_sl", "price_tp", "price_trigger", "rate_margin", "reason", "side", "status", "symbol", "symbol_id", "time_done", "time_expiration", "time_setup", "type", "type_fill", "type_time", "updated_at", "updated_by", "volume_current", "volume_current_ext", "volume_initial", "volume_initial_ext"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of position
        if self.position:
            _dict['position'] = self.position.to_dict()
        # override the default output from pydantic by calling `to_dict()` of position_by
        if self.position_by:
            _dict['position_by'] = self.position_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of symbol
        if self.symbol:
            _dict['symbol'] = self.symbol.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": ModelTradeAccount.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "account_id": obj.get("account_id"),
            "comment": obj.get("comment"),
            "contract_size": obj.get("contract_size"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "dealer_id": obj.get("dealer_id"),
            "digits": obj.get("digits"),
            "digits_currency": obj.get("digits_currency"),
            "exit_level": obj.get("exit_level"),
            "exit_loos": obj.get("exit_loos"),
            "exit_profit": obj.get("exit_profit"),
            "expiration_policy": obj.get("expiration_policy"),
            "external_id": obj.get("external_id"),
            "id": obj.get("id"),
            "position": ModelPosition.from_dict(obj["position"]) if obj.get("position") is not None else None,
            "position_by": ModelPosition.from_dict(obj["position_by"]) if obj.get("position_by") is not None else None,
            "position_by_id": obj.get("position_by_id"),
            "position_id": obj.get("position_id"),
            "price_current": obj.get("price_current"),
            "price_order": obj.get("price_order"),
            "price_sl": obj.get("price_sl"),
            "price_tp": obj.get("price_tp"),
            "price_trigger": obj.get("price_trigger"),
            "rate_margin": obj.get("rate_margin"),
            "reason": obj.get("reason"),
            "side": obj.get("side"),
            "status": obj.get("status"),
            "symbol": ModelSymbol.from_dict(obj["symbol"]) if obj.get("symbol") is not None else None,
            "symbol_id": obj.get("symbol_id"),
            "time_done": obj.get("time_done"),
            "time_expiration": obj.get("time_expiration"),
            "time_setup": obj.get("time_setup"),
            "type": obj.get("type"),
            "type_fill": obj.get("type_fill"),
            "type_time": obj.get("type_time"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by"),
            "volume_current": obj.get("volume_current"),
            "volume_current_ext": obj.get("volume_current_ext"),
            "volume_initial": obj.get("volume_initial"),
            "volume_initial_ext": obj.get("volume_initial_ext")
        })
        return _obj

from omtrader.rest.models.model_position import ModelPosition
from omtrader.rest.models.model_trade_account import ModelTradeAccount
# TODO: Rewrite to not use raise_errors
ModelOrder.model_rebuild(raise_errors=False)

