# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelEmploymentStatus(int, Enum):
    """
    ModelEmploymentStatus
    """

    """
    allowed enum values
    """
    EmploymentStatus_unemployed = 0
    EmploymentStatus_employed = 1
    EmploymentStatus_self_employed = 2
    EmploymentStatus_retired = 3
    EmploymentStatus_student = 4
    EmploymentStatus_other = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelEmploymentStatus from a JSON string"""
        return cls(json.loads(json_str))


