# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelSwaptype(int, Enum):
    """
    ModelSwaptype
    """

    """
    allowed enum values
    """
    Swaptype_points = 0
    SwapType_in_money = 1
    SwapType_current_price = 2
    SwapType_open_price = 3

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelSwaptype from a JSON string"""
        return cls(json.loads(json_str))


