# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelExpirationPolicy(int, Enum):
    """
    ModelExpirationPolicy
    """

    """
    allowed enum values
    """
    ExpirationPolicy_good_till_canceled = 0
    ExpirationPolicy_day = 1
    ExpirationPolicy_specified_time = 2
    ExpirationPolicy_specified_day = 3

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelExpirationPolicy from a JSON string"""
        return cls(json.loads(json_str))


