# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelCalcType(int, Enum):
    """
    ModelCalcType
    """

    """
    allowed enum values
    """
    CalcType_Forex = 0
    CalcType_Forex_No_Leverage = 1
    CalcType_CFD = 2
    CalcType_CFD_Leverage = 3
    CalcType_Futures = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelCalcType from a JSON string"""
        return cls(json.loads(json_str))


