# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelReasonType(int, Enum):
    """
    ModelReasonType
    """

    """
    allowed enum values
    """
    ReasonType_client = 0
    ReasonType_script_type = 1
    ReasonType_dealer = 2
    ReasonType_stop_loss = 3
    ReasonType_take_profit = 4
    ReasonType_take_profit_stop_loss = 5
    ReasonType_stop_out = 6
    ReasonType_rollover = 7
    ReasonType_external_client = 8
    ReasonType_variation_margin = 9
    ReasonType_gateway = 10
    ReasonType_signal = 11
    ReasonType_settlement = 12
    ReasonType_transfer = 13
    ReasonType_synchronization = 14
    ReasonType_external_service = 15
    ReasonType_mobile_type = 16
    ReasonType_web_type = 17
    ReasonType_split = 18
    ReasonType_migration = 19

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelReasonType from a JSON string"""
        return cls(json.loads(json_str))


