# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelClientPreferredMethod(int, Enum):
    """
    ModelClientPreferredMethod
    """

    """
    allowed enum values
    """
    ClientPreferredMethod_not_specified = 0
    ClientPreferredMethod_email = 1
    ClientPreferredMethod_phone = 2
    ClientPreferredMethod_sms = 3
    ClientPreferredMethod_messenger = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelClientPreferredMethod from a JSON string"""
        return cls(json.loads(json_str))


