# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelSymbolStatus(int, Enum):
    """
    ModelSymbolStatus
    """

    """
    allowed enum values
    """
    SymbolStatusType_enabled = 0
    SymbolStatusType_disabled = 1
    SymbolStatusType_trade_closed_quote_closed = 2
    SymbolStatusType_trade_closed_quote_open = 3
    SymbolStatusType_trade_open_quote_closed = 4
    SymbolStatusType_timeouted = 5
    SymbolStatusType_time_limit_expired = 6

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelSymbolStatus from a JSON string"""
        return cls(json.loads(json_str))


