# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelDocumentType(int, Enum):
    """
    ModelDocumentType
    """

    """
    allowed enum values
    """
    DocumentType_passport = 0
    DocumentType_driver_license = 1
    DocumentType_national_id = 2

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelDocumentType from a JSON string"""
        return cls(json.loads(json_str))


