# coding: utf-8

"""
    OMTrader Trader's API

    OMTrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "omtrader-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
    "requests >= 2.25.0",
    "websocket-client >= 1.0.0",
]

setup(
    name=NAME,
    version=VERSION,
    description="OMTrader Python SDK - REST and WebSocket API Client",
    author="API Support",
    author_email="support@omtrader.io",
    url="",
    keywords=["OMTrader", "Trading", "API", "REST", "WebSocket", "SDK", "Python"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests", "openapi_client"]),
    include_package_data=True,
    license="MIT License",
    long_description_content_type='text/markdown',
    long_description="""\
    OMTrader Python SDK - The official Python client library for the OMTrader REST and WebSocket APIs.
    """,  # noqa: E501
)