# coding: utf-8

# flake8: noqa
"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.http_http_response import HttpHttpResponse
from openapi_client.models.messaging_cancel_order import MessagingCancelOrder
from openapi_client.models.messaging_close_position import MessagingClosePosition
from openapi_client.models.messaging_crt_order import MessagingCrtOrder
from openapi_client.models.messaging_history_tick import MessagingHistoryTick
from openapi_client.models.messaging_open_account import MessagingOpenAccount
from openapi_client.models.messaging_trader_order_approval import MessagingTraderOrderApproval
from openapi_client.models.messaging_upt_order import MessagingUptOrder
from openapi_client.models.messaging_upt_position import MessagingUptPosition
from openapi_client.models.messaging_view_symbol import MessagingViewSymbol
from openapi_client.models.model_calc_type import ModelCalcType
from openapi_client.models.model_channel_type import ModelChannelType
from openapi_client.models.model_client import ModelClient
from openapi_client.models.model_client_preferred_method import ModelClientPreferredMethod
from openapi_client.models.model_client_status import ModelClientStatus
from openapi_client.models.model_client_type import ModelClientType
from openapi_client.models.model_conversion_type import ModelConversionType
from openapi_client.models.model_data_source import ModelDataSource
from openapi_client.models.model_deal import ModelDeal
from openapi_client.models.model_direction_type import ModelDirectionType
from openapi_client.models.model_document_type import ModelDocumentType
from openapi_client.models.model_education_level import ModelEducationLevel
from openapi_client.models.model_employment_industry import ModelEmploymentIndustry
from openapi_client.models.model_employment_status import ModelEmploymentStatus
from openapi_client.models.model_execution_mode import ModelExecutionMode
from openapi_client.models.model_exit_level import ModelExitLevel
from openapi_client.models.model_expiration_policy import ModelExpirationPolicy
from openapi_client.models.model_fill_policy import ModelFillPolicy
from openapi_client.models.model_group import ModelGroup
from openapi_client.models.model_group_type import ModelGroupType
from openapi_client.models.model_kyc_status import ModelKycStatus
from openapi_client.models.model_liqudation_status import ModelLiqudationStatus
from openapi_client.models.model_margin_mode import ModelMarginMode
from openapi_client.models.model_order import ModelOrder
from openapi_client.models.model_order_status import ModelOrderStatus
from openapi_client.models.model_order_type import ModelOrderType
from openapi_client.models.model_position import ModelPosition
from openapi_client.models.model_position_status import ModelPositionStatus
from openapi_client.models.model_reason_type import ModelReasonType
from openapi_client.models.model_role import ModelRole
from openapi_client.models.model_role_type import ModelRoleType
from openapi_client.models.model_side_type import ModelSideType
from openapi_client.models.model_source_of_wealth import ModelSourceOfWealth
from openapi_client.models.model_swaptype import ModelSwaptype
from openapi_client.models.model_symbol import ModelSymbol
from openapi_client.models.model_symbol_class import ModelSymbolClass
from openapi_client.models.model_symbol_status import ModelSymbolStatus
from openapi_client.models.model_trade_account import ModelTradeAccount
from openapi_client.models.model_trade_level import ModelTradeLevel
from openapi_client.models.model_trade_type import ModelTradeType
from openapi_client.models.model_trading_experience import ModelTradingExperience
