# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelConversionType(int, Enum):
    """
    ModelConversionType
    """

    """
    allowed enum values
    """
    ConversionType_Multiply = 0
    ConversionType_Divide = 1

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelConversionType from a JSON string"""
        return cls(json.loads(json_str))


