# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelSourceOfWealth(int, Enum):
    """
    ModelSourceOfWealth
    """

    """
    allowed enum values
    """
    SourceOfWealth_employment_or_business_proceeds = 0
    SourceOfWealth_savings_or_investments = 1
    SourceOfWealth_gifts_or_inheritance = 2
    SourceOfWealth_other = 3

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelSourceOfWealth from a JSON string"""
        return cls(json.loads(json_str))


