# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelClientStatus(int, Enum):
    """
    ModelClientStatus
    """

    """
    allowed enum values
    """
    ClientStatus_unregistered = 0
    ClientStatus_registered = 1
    ClientStatus_not_interested = 2
    ClientStatus_incompleted = 3
    ClientStatus_completed = 4
    ClientStatus_information = 5
    ClientStatus_rejected = 6
    ClientStatus_approved = 7
    ClientStatus_funded = 8
    ClientStatus_active = 9
    ClientStatus_inactive = 10
    ClientStatus_suspend = 11
    ClientStatus_closed = 12
    ClientStatus_terminated = 13

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelClientStatus from a JSON string"""
        return cls(json.loads(json_str))


