# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.model_symbol import ModelSymbol
from typing import Optional, Set
from typing_extensions import Self

class ModelSymbolClass(BaseModel):
    """
    ModelSymbolClass
    """ # noqa: E501
    desc: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    parent_id: Optional[StrictInt] = None
    symbol_classes: Optional[List[ModelSymbolClass]] = None
    symbols: Optional[List[ModelSymbol]] = None
    __properties: ClassVar[List[str]] = ["desc", "id", "parent_id", "symbol_classes", "symbols"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelSymbolClass from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in symbol_classes (list)
        _items = []
        if self.symbol_classes:
            for _item_symbol_classes in self.symbol_classes:
                if _item_symbol_classes:
                    _items.append(_item_symbol_classes.to_dict())
            _dict['symbol_classes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in symbols (list)
        _items = []
        if self.symbols:
            for _item_symbols in self.symbols:
                if _item_symbols:
                    _items.append(_item_symbols.to_dict())
            _dict['symbols'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelSymbolClass from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "desc": obj.get("desc"),
            "id": obj.get("id"),
            "parent_id": obj.get("parent_id"),
            "symbol_classes": [ModelSymbolClass.from_dict(_item) for _item in obj["symbol_classes"]] if obj.get("symbol_classes") is not None else None,
            "symbols": [ModelSymbol.from_dict(_item) for _item in obj["symbols"]] if obj.get("symbols") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
ModelSymbolClass.model_rebuild(raise_errors=False)

