# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelTradeLevel(int, Enum):
    """
    ModelTradeLevel
    """

    """
    allowed enum values
    """
    TradeLevel_Full = 0
    TradeLevel_Buy = 1
    TradeLevel_Sell = 2
    TradeLevel_Close = 3
    TradeLevel_Disabled = 4

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelTradeLevel from a JSON string"""
        return cls(json.loads(json_str))


