# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelOrderType(int, Enum):
    """
    ModelOrderType
    """

    """
    allowed enum values
    """
    OrderType_market_order = 0
    OrderType_buy_limit = 1
    OrderType_buy_stop = 2
    OrderType_sell_limit = 3
    OrderType_sell_stop = 4
    OrderType_buy_stop_limit = 5
    OrderType_sell_stop_limit = 6

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelOrderType from a JSON string"""
        return cls(json.loads(json_str))


