# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelOrderStatus(int, Enum):
    """
    ModelOrderStatus
    """

    """
    allowed enum values
    """
    OrderStatus_placed = 0
    OrderStatus_started = 1
    OrderStatus_partially_filled = 2
    OrderStatus_filled = 3
    OrderStatus_canceled = 4
    OrderStatus_rejected = 5
    OrderStatus_expired = 6
    OrderStatus_requoted = 7

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelOrderStatus from a JSON string"""
        return cls(json.loads(json_str))


