# coding: utf-8

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ModelLiqudationStatus(int, Enum):
    """
    ModelLiqudationStatus
    """

    """
    allowed enum values
    """
    LiqudationStatus_Healthy = 0
    LiqudationStatus_MarginCallReached = 1
    LiqudationStatus_MarginStopOutReached = 2

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ModelLiqudationStatus from a JSON string"""
        return cls(json.loads(json_str))


