# coding: utf-8

# flake8: noqa

"""
    Omtrader Trader's API

    Omtrader Trader's API docs

    The version of the OpenAPI document: 1.0
    Contact: support@omtrader.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccountsApi",
    "DealsApi",
    "OrdersApi",
    "PositionsApi",
    "SymbolsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HttpHttpResponse",
    "MessagingCancelOrder",
    "MessagingClosePosition",
    "MessagingCrtOrder",
    "MessagingHistoryTick",
    "MessagingOpenAccount",
    "MessagingTraderOrderApproval",
    "MessagingUptOrder",
    "MessagingUptPosition",
    "MessagingViewSymbol",
    "ModelCalcType",
    "ModelChannelType",
    "ModelClient",
    "ModelClientPreferredMethod",
    "ModelClientStatus",
    "ModelClientType",
    "ModelConversionType",
    "ModelDataSource",
    "ModelDeal",
    "ModelDirectionType",
    "ModelDocumentType",
    "ModelEducationLevel",
    "ModelEmploymentIndustry",
    "ModelEmploymentStatus",
    "ModelExecutionMode",
    "ModelExitLevel",
    "ModelExpirationPolicy",
    "ModelFillPolicy",
    "ModelGroup",
    "ModelGroupType",
    "ModelKycStatus",
    "ModelLiqudationStatus",
    "ModelMarginMode",
    "ModelOrder",
    "ModelOrderStatus",
    "ModelOrderType",
    "ModelPosition",
    "ModelPositionStatus",
    "ModelReasonType",
    "ModelRole",
    "ModelRoleType",
    "ModelSideType",
    "ModelSourceOfWealth",
    "ModelSwaptype",
    "ModelSymbol",
    "ModelSymbolClass",
    "ModelSymbolStatus",
    "ModelTradeAccount",
    "ModelTradeLevel",
    "ModelTradeType",
    "ModelTradingExperience",
]

# import apis into sdk package
from openapi_client.api.accounts_api import AccountsApi as AccountsApi
from openapi_client.api.deals_api import DealsApi as DealsApi
from openapi_client.api.orders_api import OrdersApi as OrdersApi
from openapi_client.api.positions_api import PositionsApi as PositionsApi
from openapi_client.api.symbols_api import SymbolsApi as SymbolsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.http_http_response import HttpHttpResponse as HttpHttpResponse
from openapi_client.models.messaging_cancel_order import MessagingCancelOrder as MessagingCancelOrder
from openapi_client.models.messaging_close_position import MessagingClosePosition as MessagingClosePosition
from openapi_client.models.messaging_crt_order import MessagingCrtOrder as MessagingCrtOrder
from openapi_client.models.messaging_history_tick import MessagingHistoryTick as MessagingHistoryTick
from openapi_client.models.messaging_open_account import MessagingOpenAccount as MessagingOpenAccount
from openapi_client.models.messaging_trader_order_approval import MessagingTraderOrderApproval as MessagingTraderOrderApproval
from openapi_client.models.messaging_upt_order import MessagingUptOrder as MessagingUptOrder
from openapi_client.models.messaging_upt_position import MessagingUptPosition as MessagingUptPosition
from openapi_client.models.messaging_view_symbol import MessagingViewSymbol as MessagingViewSymbol
from openapi_client.models.model_calc_type import ModelCalcType as ModelCalcType
from openapi_client.models.model_channel_type import ModelChannelType as ModelChannelType
from openapi_client.models.model_client import ModelClient as ModelClient
from openapi_client.models.model_client_preferred_method import ModelClientPreferredMethod as ModelClientPreferredMethod
from openapi_client.models.model_client_status import ModelClientStatus as ModelClientStatus
from openapi_client.models.model_client_type import ModelClientType as ModelClientType
from openapi_client.models.model_conversion_type import ModelConversionType as ModelConversionType
from openapi_client.models.model_data_source import ModelDataSource as ModelDataSource
from openapi_client.models.model_deal import ModelDeal as ModelDeal
from openapi_client.models.model_direction_type import ModelDirectionType as ModelDirectionType
from openapi_client.models.model_document_type import ModelDocumentType as ModelDocumentType
from openapi_client.models.model_education_level import ModelEducationLevel as ModelEducationLevel
from openapi_client.models.model_employment_industry import ModelEmploymentIndustry as ModelEmploymentIndustry
from openapi_client.models.model_employment_status import ModelEmploymentStatus as ModelEmploymentStatus
from openapi_client.models.model_execution_mode import ModelExecutionMode as ModelExecutionMode
from openapi_client.models.model_exit_level import ModelExitLevel as ModelExitLevel
from openapi_client.models.model_expiration_policy import ModelExpirationPolicy as ModelExpirationPolicy
from openapi_client.models.model_fill_policy import ModelFillPolicy as ModelFillPolicy
from openapi_client.models.model_group import ModelGroup as ModelGroup
from openapi_client.models.model_group_type import ModelGroupType as ModelGroupType
from openapi_client.models.model_kyc_status import ModelKycStatus as ModelKycStatus
from openapi_client.models.model_liqudation_status import ModelLiqudationStatus as ModelLiqudationStatus
from openapi_client.models.model_margin_mode import ModelMarginMode as ModelMarginMode
from openapi_client.models.model_order import ModelOrder as ModelOrder
from openapi_client.models.model_order_status import ModelOrderStatus as ModelOrderStatus
from openapi_client.models.model_order_type import ModelOrderType as ModelOrderType
from openapi_client.models.model_position import ModelPosition as ModelPosition
from openapi_client.models.model_position_status import ModelPositionStatus as ModelPositionStatus
from openapi_client.models.model_reason_type import ModelReasonType as ModelReasonType
from openapi_client.models.model_role import ModelRole as ModelRole
from openapi_client.models.model_role_type import ModelRoleType as ModelRoleType
from openapi_client.models.model_side_type import ModelSideType as ModelSideType
from openapi_client.models.model_source_of_wealth import ModelSourceOfWealth as ModelSourceOfWealth
from openapi_client.models.model_swaptype import ModelSwaptype as ModelSwaptype
from openapi_client.models.model_symbol import ModelSymbol as ModelSymbol
from openapi_client.models.model_symbol_class import ModelSymbolClass as ModelSymbolClass
from openapi_client.models.model_symbol_status import ModelSymbolStatus as ModelSymbolStatus
from openapi_client.models.model_trade_account import ModelTradeAccount as ModelTradeAccount
from openapi_client.models.model_trade_level import ModelTradeLevel as ModelTradeLevel
from openapi_client.models.model_trade_type import ModelTradeType as ModelTradeType
from openapi_client.models.model_trading_experience import ModelTradingExperience as ModelTradingExperience

